# Generated by Django 6.0 on 2026-01-04 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dht11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(blank=True, null=True)),
                ('hum', models.FloatField(blank=True, null=True)),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dt'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('counter', models.IntegerField(default=0)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(default=0)),
                ('op1_ack', models.BooleanField(default=False)),
                ('op2_ack', models.BooleanField(default=False)),
                ('op3_ack', models.BooleanField(default=False)),
                ('op1_comment', models.TextField(blank=True)),
                ('op2_comment', models.TextField(blank=True)),
                ('op3_comment', models.TextField(blank=True)),
                ('op1_saved_at', models.DateTimeField(blank=True, null=True)),
                ('op2_saved_at', models.DateTimeField(blank=True, null=True)),
                ('op3_saved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('OPERATEUR', 'Opérateur')], default='OPERATEUR', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
